{% set name = "nuscenes-devkit" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nutonomy/nuscenes-devkit/archive/{{ version }}.tar.gz
  sha256: f7571d6fee5fa825d192813138ab0777982146ad8157cd2535b6e370e8dd9245
  patches:
    - patches/0001-Use-os-specific-path-seperator.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install ./setup -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - cachetools
    - descartes
    - fire
    - flake8
    - flake8-import-order
    - jupyter
    - matplotlib
    - numpy
    - parameterized
    - pillow >6.2.1
    - py-opencv >=4.5.4.58
    - pycocotools >=2.0.1
    - pyquaternion >=0.9.5
    - scikit-learn
    - scipy
    - shapely
    - tqdm

test:
  imports:
    - nuscenes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nutonomy/nuscenes-devkit
  summary: The devkit of the nuScenes dataset
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeongseok-meta
