schema_version: 1

context:
  name: nuscenes-devkit
  version: "1.2.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/nutonomy/nuscenes-devkit/archive/${{ version }}.tar.gz
  sha256: f7571d6fee5fa825d192813138ab0777982146ad8157cd2535b6e370e8dd9245
  patches:
    - patches/0001-Use-os-specific-path-seperator.patch

build:
  noarch: python
  number: 1
  script: ${{ PYTHON }} -m pip install ./setup -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - cachetools
    - descartes
    - fire
    - matplotlib-base >=3.6.0
    - numpy >=1.22.0,<2.0.0
    - parameterized
    - pillow >6.2.1
    - py-opencv >=4.5.4.58
    - pycocotools >=2.0.1
    - pyquaternion >=0.9.5
    - scikit-learn
    - scipy
    - shapely ~=2.0.3
    - tqdm

tests:
  - python:
      imports:
        - nuimages
        - nuscenes
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pip check
      - python run_test.py
    files:
      recipe:
        - run_test.py
    requirements:
      run:
        - pip
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/nutonomy/nuscenes-devkit
  repository: https://github.com/nutonomy/nuscenes-devkit
  summary: The devkit of the nuScenes dataset
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeongseok-meta
